spring.application.name=smapi
spring.jackson.default-property-inclusion=non_null

spring.datasource.url=jdbc:postgresql://localhost:5432/smapi
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.continue-on-error=false
spring.sql.init.mode=always

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}